brace_style = "AlwaysNextLine"
combine_control_expr = false
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
imports_layout = "Vertical"
imports_granularity = "Module"
tab_spaces = 8
max_width = 140
